// Auto-generated by generate_config_header.py. DO NOT EDIT.
#ifndef SENSORSCONFIG_H_H
#define SENSORSCONFIG_H_H

#include <stdint.h>
#include "DataTypes.h"

#define SENSORS_DEBUG 0

typedef struct {
  uint8_t measurement_id;
  const char* name;
  const char* unit;
} MeasurementInfo;

typedef struct {
  uint16_t sensor_id;          // user-defined id
  const char* config_key;      // YAML key for this sensor
  const char* part_name;       // human part name (e.g. Plantower PMS7003)
  const char* type;            // sensor 'type' used by factory
  CommsType comms;
  int32_t port_no;             // port number (I2C bus index / UART index) or -1
  int16_t rx_pin;              // optional, -1 if unused
  int16_t tx_pin;              // optional, -1 if unused
  int32_t baud_rate;           // optional, -1 if unused
  const MeasurementInfo* measurements;
  uint8_t measurement_count;
} SensorInfo;

// Measurement arrays
static const MeasurementInfo TVOCSENSOR_MEASUREMENTS[] = {
  { (uint8_t)1, "tvoc", "ppb" },
};

static const MeasurementInfo PMSENSOR_MEASUREMENTS[] = {
  { (uint8_t)2, "pm2.5", "ppm" },
};

static const MeasurementInfo FORMALDEHYDESENSOR_MEASUREMENTS[] = {
  { (uint8_t)1, "tvoc", "ppb" },
};

// Sensor table
static const SensorInfo sensors_config[] = {
  { (uint16_t)1, "TVOCSensor", "ZE40A-TVOC", "TVOCSensor", COMM_HARDWARE_SERIAL, (int32_t)0, (int16_t)-1, (int16_t)-1, (int32_t)9600, TVOCSENSOR_MEASUREMENTS, (uint8_t)1 },
  { (uint16_t)2, "PMSensor", "Plantower PMS7003", "PMSensor", COMM_I2C, (int32_t)1, (int16_t)-1, (int16_t)-1, (int32_t)-1, PMSENSOR_MEASUREMENTS, (uint8_t)1 },
  { (uint16_t)3, "FormaldehydeSensor", "DARTSENSORS WZ-S-K", "CH2OSensor", COMM_SOFTWARE_SERIAL, (int32_t)-1, (int16_t)12, (int16_t)13, (int32_t)9600, FORMALDEHYDESENSOR_MEASUREMENTS, (uint8_t)1 },
};

#define SENSOR_COUNT 3

// Convenience macros for sensor IDs and measurement IDs
#define SENSOR_ID_TVOCSENSOR 1
#define MEAS_TVOCSENSOR_TVOC 1

#define SENSOR_ID_PMSENSOR 2
#define MEAS_PMSENSOR_PM2_5 2

#define SENSOR_ID_FORMALDEHYDESENSOR 3
#define MEAS_FORMALDEHYDESENSOR_TVOC 1

// Debug helpers: arrays of names (useful when SENSORS_DEBUG == 1)
static const char* const sensor_config_key[] = {
  "TVOCSensor",
  "PMSensor",
  "FormaldehydeSensor",
};

static const char* const sensor_part_name[] = {
  "ZE40A-TVOC",
  "Plantower PMS7003",
  "DARTSENSORS WZ-S-K",
};

// For debug: measurement names by sensor (array of arrays).
static const MeasurementInfo* const sensor_measurements[] = {
  TVOCSENSOR_MEASUREMENTS,
  PMSENSOR_MEASUREMENTS,
  FORMALDEHYDESENSOR_MEASUREMENTS,
};

/*
  Factory note:
  - You must provide factory functions that create your sensor objects (polymorphic).
  - For example, for type "PMSensor" you could implement:
      #ifdef __cplusplus
      class SensorBase; // forward
      extern SensorBase* createPMSensor(const SensorInfo* cfg);
      #endif
  - Then at startup you can iterate sensors_config[] and call the correct factory
    based on sensors_config[i].type (string) or create a compile-time mapping.
*/

#endif // SENSORSCONFIG_H_H
