// Auto-generated by generate_config_header.py. DO NOT EDIT.
#ifndef SENSORSCONFIG_H_H
#define SENSORSCONFIG_H_H

#include <stdint.h>
#include "DataTypes.h"

#define SENSORS_DEBUG 1

#define NODE_ID "A01"
#define SAMPLING_RATE 3000

typedef struct {
  uint8_t measurement_id;
  const char* name;
  const char* unit;
} MeasurementInfo;

typedef struct {
  uint16_t sensor_id;          // user-defined id
  const char* config_key;      // YAML key for this sensor
  const char* part_name;       // human part name (e.g. Plantower PMS7003)
  const char* type;            // sensor 'type' used by factory
  CommsType comms;
  int32_t port_no;             // port number (I2C bus index / UART index) or -1
  uint16_t i2c_address;        // i2c address of sensor or -1
  int16_t rx_pin;              // optional, -1 if unused
  int16_t tx_pin;              // optional, -1 if unused
  int32_t baud_rate;           // optional, -1 if unused
  const MeasurementInfo* measurements;
  uint8_t measurement_count;
} SensorInfo;

// Measurement arrays
static const MeasurementInfo PMSENSOR_MEASUREMENTS[] = {
  { (uint8_t)4, "PM1.0 (atmospheric)", "µg/m³" },
  { (uint8_t)5, "PM2.5 (atmospheric)", "µg/m³" },
  { (uint8_t)6, "PM10 (atmospheric)", "µg/m³" },
  { (uint8_t)12, "Particle count ≥ 10 µm", "particles / 0.1 L" },
};

// Sensor table
static const SensorInfo sensors_config[] = {
  { (uint16_t)2, "PMSensor", "Plantower PMS7003", "PMS7003Sensor", COMM_HARDWARE_SERIAL, (int32_t)2, (uint16_t)-1, (int16_t)-1, (int16_t)-1, (int32_t)9600, PMSENSOR_MEASUREMENTS, (uint8_t)4 },
};

#define SENSOR_COUNT 1

// Convenience macros for sensor IDs and measurement IDs
#define SENSOR_ID_PMSENSOR 2
#define MEAS_PMSENSOR_PM1_0_ATMOSPHERIC 4
#define MEAS_PMSENSOR_PM2_5_ATMOSPHERIC 5
#define MEAS_PMSENSOR_PM10_ATMOSPHERIC 6
#define MEAS_PMSENSOR_PARTICLE_COUNT_10_M 12

// Debug helpers: arrays of names (useful when SENSORS_DEBUG == 1)
static const char* const sensor_config_key[] = {
  "PMSensor",
};

static const char* const sensor_part_name[] = {
  "Plantower PMS7003",
};

// For debug: measurement names by sensor (array of arrays).
static const MeasurementInfo* const sensor_measurements[] = {
  PMSENSOR_MEASUREMENTS,
};

/*
  Factory note:
  - You must provide factory functions that create your sensor objects (polymorphic).
  - For example, for type "PMSensor" you could implement:
      #ifdef __cplusplus
      class SensorBase; // forward
      extern SensorBase* createPMSensor(const SensorInfo* cfg);
      #endif
  - Then at startup you can iterate sensors_config[] and call the correct factory
    based on sensors_config[i].type (string) or create a compile-time mapping.
*/

#endif // SENSORSCONFIG_H_H
