// Generated by ChatGPT

#include <Arduino.h>
#include <SFE_BMP180.h>
#include <Wire.h>
#include <unity.h>

SFE_BMP180 pressure;
#define ALTITUDE 1655.0

double T, P, p0, a;

// --- TESTS ---
void test_sensor_init(void) {
    TEST_ASSERT_TRUE_MESSAGE(pressure.begin(), "BMP180 init failed");
}

void test_temperature_reading(void) {
    char status = pressure.startTemperature();
    TEST_ASSERT_TRUE(status > 0);

    delay(status);
    status = pressure.getTemperature(T);
    TEST_ASSERT_TRUE(status > 0);

    // Temperature should be in a sane range (-40°C to +85°C typical)
    TEST_ASSERT_FLOAT_WITHIN(100, 25.0, T);  
}

void test_pressure_reading(void) {
    char status = pressure.startPressure(3);
    TEST_ASSERT_TRUE(status > 0);

    delay(status);
    status = pressure.getPressure(P, T);
    TEST_ASSERT_TRUE(status > 0);

    // Pressure at Earth’s surface should be roughly 300–1100 hPa
    TEST_ASSERT_FLOAT_WITHIN(1000, 1013.25, P);  
}

void test_altitude_computation(void) {
    p0 = pressure.sealevel(P, ALTITUDE);
    a = pressure.altitude(P, p0);

    // Check altitude is within ~200m of expected
    TEST_ASSERT_FLOAT_WITHIN(200, ALTITUDE, a);
}

// --- UNITY ENTRYPOINT ---
void setup() {
    delay(2000);
    Serial.begin(9600);
    UNITY_BEGIN();

    RUN_TEST(test_sensor_init);
    RUN_TEST(test_temperature_reading);
    RUN_TEST(test_pressure_reading);
    RUN_TEST(test_altitude_computation);

    UNITY_END();
}

void loop() {
    // not used
}
